## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per environment.
authorizations: &AUTHORIZATIONS
  host: <%= ENV['LDAP_HOST'] || 'localhost' %>
  allow_unauthenticated_bind: <%= ENV['LDAP_UNAUTHENTICATED_BIND'] || false %>
  group_base: <%= ENV['LDAP_GROUP_BASE'] || 'ou=groups,dc=test,dc=com' %>
  base: <%= ENV['LDAP_BASE'] || 'ou=people,dc=test,dc=com' %>
  # The name of the email attribute in the LDAP server
  attribute: <%= ENV['LDAP_ATTRIBUTE'] || 'mail' %>
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  # required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    # - cn=admins,ou=groups,dc=test,dc=com
    # - cn=users,ou=groups,dc=test,dc=com
    # If an array is given, the first element will be the attribute to check against, the second the group name
    # - ["moreMembers", "cn=users,ou=groups,dc=test,dc=com"]
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  # require_attribute:
  #   objectClass: inetOrgPerson
  #   authorizationRole: postsAdmin
  ## Requires config.ldap_check_attributes_presence in devise.rb to be true
  ## Can have multiple attributes set to true or false to check presence, all must match all to be authorized
  require_attribute_presence:
    mail: true

## Environment

development:
  <<: *AUTHORIZATIONS
  port: <%= ENV['LDAP_PORT'] || 389 %>
  admin_user: cn=admin,dc=test,dc=com
  admin_password: <%= ENV['LDAP_ADMIN_PASS'] %>
  ssl: <% ENV['LDAP_SSL_MODE'] || false %>

test:
  <<: *AUTHORIZATIONS
  port: <%= ENV['LDAP_PORT'] || 3389 %>
  admin_user: cn=admin,dc=test,dc=com
  admin_password: <%= ENV['LDAP_ADMIN_PASS'] %>
  ssl: <% ENV['LDAP_SSL_MODE'] || 'simple_tls' %>

production:
  <<: *AUTHORIZATIONS
  port: <%= ENV['LDAP_PORT'] || 636 %>
  admin_user: <%= ENV['LDAP_ADMIN_USER'] || 'cn=admin,dc=test,dc=com' %>
  admin_password: <%= ENV['LDAP_ADMIN_PASS'] %>
  ssl: <% ENV['LDAP_SSL_MODE'] || 'start_tls' %>
