name: Push Vulcan to Heroku on every merge to master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add heroku remote
        run: heroku git:remote -a mitre-vulcan-staging
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "mitre-vulcan-staging"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
